tasks:
- install:
    extra_packages:
      deb:
        - ceph-osd-crimson
        - ceph-osd-crimson-dbg
      rpm:
        - ceph-osd-crimson
        - ceph-osd-crimson-debuginfo
    extra_system_packages:
      deb:
        - wget
      rpm:
        - wget
- pexec:
    all:
      - sudo update-alternatives --set ceph-osd /usr/bin/ceph-osd-crimson
